### ISSUE TITLE
MOAR functions

### ISSUE THREAD

**Issue by bruab** [nynhle/fasta_tools#1]
Lines 23-27 all print counts; why not extract them into a function just for fun? Define the function up above somewhere, and then at the end of the `with open` block call it, something like

    print_counts(a_count, c_count, g_count, t_count)

**Comment by nynhle** [comment]
Now the printing kind of has its own function since all the counted nucleobases are represented as instance variables. It's still horrible though. Would be more than happy if you would review the "object-oriented-tryout"-branch if you got time.
